// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const supabaseUrl = (import.meta.env.VITE_SUPABASE_URL || "").replace(/\/$/, "");
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "";
const siteUrl = (import.meta.env.VITE_PUBLIC_SITE_URL || window.location.origin).replace(/\/$/, "");

if (!supabaseUrl || !supabaseKey) {
  // Surface a clear, actionable error in dev/prod
  console.error("[Auth] Missing Supabase envs. Check VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY before build.");
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
});

export const authRedirectTo = (path = "/auth") => `${siteUrl}${path}`;