// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// CRITICAL: These are PUBLIC keys safe for client-side use
// The anon key has RLS policies enforced - no sensitive data exposure
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL!;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY!;
const SITE_URL = import.meta.env.VITE_PUBLIC_SITE_URL || window.location.origin;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'X-Client-Info': 'strideguide-web',
    },
  },
});

// Helper: always build redirectTo from your configured domain
export const authRedirectTo = (path = "/app") =>
  `${SITE_URL.replace(/\/$/, "")}${path}`;